namespace AnotherWeatherForecast.Application.Common.Models;

/// <summary>
/// Problem details (RFC 7807 / RFC 9457 compatible)
/// </summary>
public class ProblemDetails
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int? Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; set; }

    /// <summary>
    /// Additional members to extend the problem details with application-specific data.
    /// </summary>
    public IDictionary<string, object?> Extensions { get; } = new Dictionary<string, object?>();
}